// B2BCalculationPageStyles.js
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFBF2",
    paddingTop: 40,
    paddingHorizontal: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 10,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    flex: 1,
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  dropdownCard: {
    backgroundColor: "#fff",
    margin: 12,
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 2,
  },
  dropdownCardSmall: {
    backgroundColor: "#fff",
    marginVertical: 6,
    padding: 12,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 1,
  },
  dropdownText: {
    marginLeft: 10,
    fontSize: 16,
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
  },
  card: {
    backgroundColor: "#fff",
    margin: 12,
    padding: 18,
    borderRadius: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  dropdownFloating: {
    position: "absolute",
    top: 130,
    left: 18,
    right: 18,
    backgroundColor: "#fff",
    borderRadius: 12,
    elevation: 10,
    zIndex: 10000,
    maxHeight: 200,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    overflow: "hidden",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  issueHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 20,
  },
  issueEntryCard: {
    position: "relative",
    overflow: "visible",
    paddingTop: 18,
  },
  issueReceiptOverlay: {
    position: "absolute",
    top: -10,
    left: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#B8860B",
    alignItems: "flex-start",
    justifyContent: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  issueReceiptOverlayLine: {
    color: "#2C3E50",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
  },
  stickyIssueReceiptBar: {
    marginHorizontal: 28,
    marginTop: 8,
    marginBottom: 2,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#B8860B",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    zIndex: 20,
  },
  stickyIssueReceiptLine: {
    color: "#2C3E50",
    fontSize: 13,
    fontWeight: "700",
  },
  greenDot: {
    width: 12,
    height: 12,
    backgroundColor: "#B8860B",
    borderRadius: 6,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: "#2C3E50",
    marginBottom: 4,
  },
  infoText: {
    fontSize: 17,
    marginVertical: 2,
  },
  label: {
    marginTop: 10,
    fontSize: 15,
    color: "#555",
  },
  subLabel: {
    fontSize: 14,
    marginBottom: 8,
    color: "#555",
  },
  goldValue: {
    fontSize: 20,
    color: "#B8860B",
    fontWeight: "700",
  },
  blackValue: {
    fontSize: 20,
    fontWeight: "700",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inputBox: {
    width: "48%",
  },
  input: {
    backgroundColor: "#F4F4F4",
    padding: 12,
    borderRadius: 10,
    fontSize: 16,
  },
  purityBox: {
    backgroundColor: "#F4F4F4",
    padding: 12,
    borderRadius: 10,
    justifyContent: "center",
  },
  purityText: {
    fontSize: 16,
    fontWeight: "600",
  },
  addBtn: {
    backgroundColor: "#B8860B",
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
    elevation: 3,
  },
  addBtnText: {
    fontSize: 17,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  holdBtn: {
    backgroundColor: "#FFF3CD",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#F2C94C",
  },
  holdBtnText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#8A5A00",
  },
  addBtn2: {
    backgroundColor: "#B8860B",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  addBtnText2: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  searchBox: {
    backgroundColor: "#fff",
    padding: 14,
    borderRadius: 12,
    fontSize: 16,
    flex: 1,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    color: "#000",
  },
  searchBtn: {
    backgroundColor: "#B8860B",
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  listItem: {
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: "#F5F5F5",
    backgroundColor: "#fff",
  },
  listItemText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#34495E",
  },
  dropdownItemContentIssue: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    backgroundColor: "#fff",
  },
  dropdownItemTextIssue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2C3E50",
    flex: 1,
  },
  dropdownItemWeightIssue: {
    fontSize: 13,
    color: "#7A5C00",
    fontWeight: "700",
    backgroundColor: "#FFF8E1",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  dropdownItemContentReceipt: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    backgroundColor: "#fff",
  },
  dropdownItemTextReceipt: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2C3E50",
    flex: 1,
  },
  dropdownItemWeightReceipt: {
    fontSize: 13,
    color: "#004D40",
    fontWeight: "700",
    backgroundColor: "#E0F2F1",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  secondTableHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#FFF0B3",
    paddingVertical: 12,
    borderRadius: 10,
    marginTop: 10,
  },
  secondTableHeaderText: {
    width: "25%",
    textAlign: "center",
    fontWeight: "700",
    fontSize: 14,
    color: "#333",
  },
  secondTableRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "#E5E5E5",
  },
  secondTableCell: {
    width: "25%",
    textAlign: "center",
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
  },
  actionText: {
    fontSize: 14,
    fontWeight: "700",
  },
  productTable: {
    width: 1260,
  },
  productTableHeader: {
    flexDirection: "row",
    backgroundColor: "#FFF9C4",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#B8860B",
  },
  productHeaderCell: {
    width: 140,
    textAlign: "center",
    fontWeight: "700",
    fontSize: 14,
    color: "#495057",
  },
  productTableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  productCell: {
    width: 140,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "600",
  },
  summaryContainer: {
    width: 1000,
  },
  summaryHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#FFF7D1",
    paddingVertical: 12,
    borderRadius: 8,
  },
  summaryHeaderText: {
    width: 140,
    textAlign: "center",
    fontWeight: "700",
    fontSize: 13,
  },
  summaryRow: {
    flexDirection: "row",
    backgroundColor: "#FFF8E6",
    paddingVertical: 12,
    borderRadius: 6,
  },
  summaryCell: {
    width: 140,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "600",
  },
  dropdown: {
    backgroundColor: "#fff",
    borderRadius: 10,
    elevation: 3,
    marginTop: 5,
    maxHeight: 200,
  },
  customerInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  customerDetails: {
    flex: 1,
  },
  customerLinkText: {
    color: "#1565C0",
    textDecorationLine: "underline",
    fontWeight: "700",
  },
  heldProcessCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "#F8FBF8",
    borderWidth: 1,
    borderColor: "#D9E8D9",
    marginTop: 10,
  },
  heldProcessName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2D3D",
  },
  heldProcessMeta: {
    fontSize: 12,
    color: "#607080",
    marginTop: 3,
  },
  heldDeleteBtn: {
    marginLeft: 12,
    padding: 6,
  },
  balanceContainer: {
    alignItems: "flex-end",
  },
  balanceText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#7F8C8D",
    marginTop: 4,
  },
  balanceLinkText: {
    color: "#1565C0",
    textDecorationLine: "underline",
    fontWeight: "700",
  },
  cartContainer: {
    position: "relative",
    marginLeft: "auto",
  },
  cartText: {
    color: "gray",
    fontSize: 14,
    fontWeight: "600",
  },
  badge: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#FF5722",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
  },
  changeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#E3F2FD",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  changeButtonText: {
    color: "#1E88E5",
    fontSize: 14,
    fontWeight: "600",
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: "#1E88E5",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: "#1E88E5",
  },
  checkboxLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
});
